ported runlocal from /bin/bash to /bin/sh

diff --git a/uml/runlocal b/uml/runlocal
--- a/uml/runlocal
+++ b/uml/runlocal
@@ -1,33 +1,40 @@
-#!/bin/bash
+#!/bin/sh
+#
+#  David Jones, ScraperWiki Limited.
+#  2011-12-21
 #
 #  Run the datastore, proxy, twister, orbited and scriptmgr servers locally,
-#  i.e. without using a real LXC
-#
+#  i.e. without using a real LXC.
+
 [ -f uml.cfg ] || {
-	echo	"runlocal: uml.cfg not found"
-	exit	1
-	}
+    echo "runlocal: uml.cfg not found;"
+    echo "runlocal: Script should be run from uml directory."
+
+    exit 1
+} 1>&2
 
 cmp -s uml.cfg uml.cfg-inhg || {
-	echo	"runlocal: warning uml.cfg different to uml.cfg-inhg"
+    echo "runlocal: warning uml.cfg different to uml.cfg-inhg"
     diff -u uml.cfg uml.cfg-inhg
-	}
+}
 
-rm	-rf	./var/log
-rm	-rf	./var/run
-mkdir 	-p 	./var/log
-mkdir 	-p 	./var/run
+rm      -rf     ./var/log
+rm      -rf     ./var/run
+mkdir   -p      ./var/log
+mkdir   -p      ./var/run
 
-export NODE_PATH=`cd ../lib/node_modules;pwd`
-echo -n 'Have set NODE_PATH to '
-echo $NODE_PATH
+NODE_PATH=`cd ../lib/node_modules;pwd`
+export NODE_PATH
+echo "Have set NODE_PATH to $NODE_PATH"
 
-cd ../services/scriptmgr
-node ./scriptmgr.js &
-cd -
-./etc/local.d/dataproxy		start
-./etc/local.d/ftpproxy		start
-./etc/local.d/httpproxy		start
-./etc/local.d/httpsproxy	start
-./etc/local.d/twister		start
-./etc/local.d/orbited		start
+(
+    cd ../services/scriptmgr
+    node ./scriptmgr.js &
+)
+
+./etc/local.d/dataproxy         start
+./etc/local.d/ftpproxy          start
+./etc/local.d/httpproxy         start
+./etc/local.d/httpsproxy        start
+./etc/local.d/twister           start
+./etc/local.d/orbited           start
